// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5_1E8wi9MBRYPMgEVOyTNCqUGvLQfQLI',
    appId: '1:160673715344:web:bd490d59ea056101583415',
    messagingSenderId: '160673715344',
    projectId: 'reviewapp-5a4f8',
    authDomain: 'reviewapp-5a4f8.firebaseapp.com',
    storageBucket: 'reviewapp-5a4f8.firebasestorage.app',
    measurementId: 'G-882LS3D09B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTa_vSq63yQgf7UxDV7p5bIL3o0LB4uiM',
    appId: '1:160673715344:android:fd3a0d52f02719f7583415',
    messagingSenderId: '160673715344',
    projectId: 'reviewapp-5a4f8',
    storageBucket: 'reviewapp-5a4f8.firebasestorage.app',
  );
}
